name: NodeJS with Grunt

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm" # Enables caching for faster builds

      # Install dependencies and run Grunt
      - name: Install dependencies and build
        run: |
          npm ci # Faster and more consistent than npm install
          npx grunt # Use npx to ensure the correct local version of Grunt
